import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="w-screen h-screen flex flex-col p-1 gap-1">

            {/* Nav Bar */}
            <div className="flex-none flex flex-row">
              <div className="" >
                <Link href="/">Home</Link>
              </div>
            </div>

            {/* Body */}
            <div className="flex-1">
              {props.children}
            </div>

          </div>
        </main>
      </body>
    </html>
  )
}
