

TYPES = [
    "Normal",
    "Fire",
    "Water",
    "Electric",
    "Grass",
    "Ice",
    "Fighting",
    "Poison",
    "Ground",
    "Flying",
    "Psychic",
    "Bug",
    "Rock",
    "Ghost",
    "Dragon",
    "Dark",
    "Steel",
    "Fairy",
]

EVENT_TYPES = [
    "Battle",
    "Trade",
    "Gift",
    "Item",
]

BALLS = [
    "Poke Ball",
    "Great Ball",
    "Ultra Ball",
    "Master Ball",
    "Safari Ball",
    "Fast Ball",
    "Level Ball",
    "Lure Ball",
    "Heavy Ball",
    "Love Ball",
    "Friend Ball",
    "Moon Ball",
    "Sport Ball",
    "Net Ball",
    "Nest Ball",
    "Repeat Ball",
    "Timer Ball",
    "Luxury Ball",
    "Premier Ball",
    "Dive Ball",
    "Dusk Ball",
    "Heal Ball",
    "Quick Ball",
    "Cherish Ball",
    "Park Ball",
    "Dream Ball",
    "Beast Ball",
    "GS Ball",
    "Love Ball",
    "Dream Ball",
    "Beast Ball",
    "GS Ball",
]